#!/usr/bin/env python
# -*- Mode: Python -*-
# Copyright (C) 2011  Johan Dahlin
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.
#

"""tool - utility for running & debugging"""

import optparse
import pprint
import sys

from gml import config

def main(args):
    parser = optparse.OptionParser()
    parser.add_option("-p", "--parse", action="store_true",
                      dest="parse", help="Parse only")
    parser.add_option("-t", "--token", action="store_true",
                      dest="token", help="Tokenize only")
    parser.add_option("-o", "--old", action="store_true",
                      dest="old", help="Use old PyGTK bindings")
    options, args = parser.parse_args(args)

    if options.old:
        config.use_pygtk = True

    from gml.parser import GMLParser
    from gml.builder import GMLBuilder

    filename = args[1]
    if options.token:
        parser = GMLParser()
        parser.tokenize(open(filename))
        pprint.pprint(parser.tokens)
    elif options.parse:
        parser = GMLParser()
        objects = parser.parse(open(filename))
        pprint.pprint([o.json() for o in objects], width=60)
    else:
        builder = GMLBuilder()
        builder.add_from_file(filename)

        for top in builder.objects:
            if hasattr(top, 'show_all'):
                top.show_all()

        builder.main()

if __name__ == '__main__':
    sys.exit(main(sys.argv))
